AWSTemplateFormatVersion: 2010-09-09
Description: "Minecraft Server stack"

Parameters:
  KeyPair:
    Description: Private SSH KeyPair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  
  MinecraftTrafficSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable incoming Minecraft traffic
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 25565
          IpProtocol: tcp
          ToPort: 25565

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      ImageId: ami-0070c5311b7677678
      InstanceType: t3.small
      Monitoring: true
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref MinecraftTrafficSecurityGroup
      Tags:
        - Key: Name
          Value: Minecraft-Server-EC2

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

Outputs:
  IPAddress:
    Description: Elastic IP Address associated with EC2 Instance
    Value: !Ref ElasticIP
