AWSTemplateFormatVersion: 2010-09-09
Description: "Minecraft Server stack"

Parameters:
  Email:
    Description: Endpoint for notifications
    Type: String
    Default: ''

Conditions:
  CreateEmailNotificationResources: !Not [!Equals [ !Ref Email, '' ] ]

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  
  MinecraftTrafficSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable incoming Minecraft traffic
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 25565
          IpProtocol: tcp
          ToPort: 25565

  SSHKey:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: !Sub '${AWS::StackName}-ec2-ssh-key'

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SSHKey
      ImageId: ami-0070c5311b7677678
      InstanceType: t3.small
      Monitoring: true
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref MinecraftTrafficSecurityGroup
      Tags:
        - Key: Name
          Value: Minecraft-Server-EC2

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

  SNSTopic:
    Type: AWS::SNS::Topic
    Condition: CreateEmailNotificationResources
    Properties: 
      TopicName: Minecraft-Server-Notifications
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email

  PowerOnEventRule:
    Type: AWS::Events::Rule
    Condition: CreateEmailNotificationResources
    Properties:
      EventPattern:
        source: [ "aws.ec2" ]
        detail-type: [ "EC2 Instance State-change Notification" ]
        detail:
          instance-id: [ !Ref EC2Instance ]
          state: [ "pending" ]
      State: ENABLED
      Targets:
      - Arn: !Ref SNSTopic
        Id: OpsTopic
        InputTransformer:
          InputTemplate: !Sub "\"Powering on Minecraft server at ${ElasticIP}.\""

  PowerOffEventRule:
    Type: AWS::Events::Rule
    Condition: CreateEmailNotificationResources
    Properties:
      EventPattern:
        source: [ "aws.ec2" ]
        detail-type: [ "EC2 Instance State-change Notification" ]
        detail:
          instance-id: [ !Ref EC2Instance ]
          state: [ "stopping" ]
      State: ENABLED
      Targets:
      - Arn: !Ref SNSTopic
        Id: OpsTopic
        InputTransformer:
          InputTemplate: !Sub "\"Powering off Minecraft server at ${ElasticIP}.\""

  SNSEventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Condition: CreateEmailNotificationResources
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: '*'
      Topics:
        - !Ref SNSTopic

Outputs:
  IPAddress:
    Description: Elastic IP Address associated with EC2 Instance
    Value: !Ref ElasticIP

  SSHKeyPairName:
    Description: The ID of the SSH Key Pair associated with the EC2 Instance
    Value: !Sub '/ec2/keypair/${SSHKey.KeyPairId}'

